[package]
name = "wasm-dicey"
version = "0.1.0"
authors = ["Stephan Luther <kvsari@gmail.com>"]
description = "Wasm frontend for dicey-dice."
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
dicey-dice = { git = "ssh://git@github.com/kvsari/dicey-dice.git", rev = "00419673f94c5b125adb932c372d9c45b924bd99" }
cfg-if = "0.1.6"
wasm-bindgen = "0.2.33"
console_error_panic_hook = { version = "0.1.5", optional = true }
